//! Do NOT edit this code.
//! It was automatically generated by Pavex.
//! All manual edits will be lost next time the code is generated.
extern crate alloc;
struct ServerState {
    router: pavex_matchit::Router<u32>,
    application_state: ApplicationState,
}
pub struct ApplicationState {
    s0: biscotti::Processor,
    s1: app::configuration::ModelController,
}
pub async fn build_application_state() -> crate::ApplicationState {
    let v0 = app::configuration::ModelController::new().await;
    let v1 = <pavex::cookie::ProcessorConfig as std::default::Default>::default();
    let v2 = <pavex::cookie::Processor as std::convert::From<
        pavex::cookie::ProcessorConfig,
    >>::from(v1);
    crate::ApplicationState {
        s0: v2,
        s1: v0,
    }
}
pub fn run(
    server_builder: pavex::server::Server,
    application_state: ApplicationState,
) -> pavex::server::ServerHandle {
    let server_state = std::sync::Arc::new(ServerState {
        router: build_router(),
        application_state,
    });
    server_builder.serve(route_request, server_state)
}
fn build_router() -> pavex_matchit::Router<u32> {
    let mut router = pavex_matchit::Router::new();
    router.insert("/api/greet/:name", 0u32).unwrap();
    router.insert("/api/ping", 1u32).unwrap();
    router.insert("/web/login", 2u32).unwrap();
    router.insert("/web/tickets", 3u32).unwrap();
    router.insert("/web/tickets/:id", 4u32).unwrap();
    router
}
async fn route_request(
    request: http::Request<hyper::body::Incoming>,
    _connection_info: Option<pavex::connection::ConnectionInfo>,
    server_state: std::sync::Arc<ServerState>,
) -> pavex::response::Response {
    let (request_head, request_body) = request.into_parts();
    #[allow(unused)]
    let request_body = pavex::request::body::RawIncomingBody::from(request_body);
    let request_head: pavex::request::RequestHead = request_head.into();
    let matched_route = match server_state.router.at(&request_head.target.path()) {
        Ok(m) => m,
        Err(_) => {
            let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter(
                    vec![],
                )
                .into();
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "*",
            );
            return route_3::entrypoint(
                    &server_state.application_state.s0,
                    &request_head,
                    matched_route_template,
                    &allowed_methods,
                )
                .await;
        }
    };
    let route_id = matched_route.value;
    #[allow(unused)]
    let url_params: pavex::request::path::RawPathParams<'_, '_> = matched_route
        .params
        .into();
    match route_id {
        0u32 => {
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "/api/greet/:name",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_1::entrypoint(
                            url_params,
                            &server_state.application_state.s0,
                            matched_route_template,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_3::entrypoint(
                            &server_state.application_state.s0,
                            &request_head,
                            matched_route_template,
                            &allowed_methods,
                        )
                        .await
                }
            }
        }
        1u32 => {
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "/api/ping",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_0::entrypoint(
                            &request_head,
                            matched_route_template,
                            &server_state.application_state.s0,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_3::entrypoint(
                            &server_state.application_state.s0,
                            &request_head,
                            matched_route_template,
                            &allowed_methods,
                        )
                        .await
                }
            }
        }
        2u32 => {
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "/web/login",
            );
            match &request_head.method {
                &pavex::http::Method::POST => {
                    route_2::entrypoint(
                            &server_state.application_state.s0,
                            request_body,
                            matched_route_template,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::POST,
                        ])
                        .into();
                    route_3::entrypoint(
                            &server_state.application_state.s0,
                            &request_head,
                            matched_route_template,
                            &allowed_methods,
                        )
                        .await
                }
            }
        }
        3u32 => {
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "/web/tickets",
            );
            match &request_head.method {
                &pavex::http::Method::POST => {
                    route_4::entrypoint(
                            &server_state.application_state.s1,
                            request_body,
                            &server_state.application_state.s0,
                            matched_route_template,
                            &request_head,
                        )
                        .await
                }
                &pavex::http::Method::GET => {
                    route_5::entrypoint(
                            &request_head,
                            &server_state.application_state.s0,
                            matched_route_template,
                            &server_state.application_state.s1,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::POST,
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_3::entrypoint(
                            &server_state.application_state.s0,
                            &request_head,
                            matched_route_template,
                            &allowed_methods,
                        )
                        .await
                }
            }
        }
        4u32 => {
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "/web/tickets/:id",
            );
            match &request_head.method {
                &pavex::http::Method::DELETE => {
                    route_6::entrypoint(
                            url_params,
                            &request_head,
                            &server_state.application_state.s0,
                            matched_route_template,
                            &server_state.application_state.s1,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::DELETE,
                        ])
                        .into();
                    route_3::entrypoint(
                            &server_state.application_state.s0,
                            &request_head,
                            matched_route_template,
                            &allowed_methods,
                        )
                        .await
                }
            }
        }
        i => unreachable!("Unknown route id: {}", i),
    }
}
pub mod route_0 {
    pub async fn entrypoint<'a, 'b>(
        s_0: &'a pavex::request::RequestHead,
        s_1: pavex::request::path::MatchedPathPattern,
        s_2: &'b biscotti::Processor,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0, s_1, s_2).await;
        response
    }
    async fn stage_1<'a, 'b>(
        s_0: &'a biscotti::Processor,
        s_1: pavex::request::path::MatchedPathPattern,
        s_2: &'b pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let response = wrapping_1(s_1, s_2).await;
        let response = post_processing_1(response, s_0).await;
        response
    }
    async fn stage_2<'a>(s_0: &'a pavex_tracing::RootSpan) -> pavex::response::Response {
        let response = handler().await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: &pavex::request::RequestHead,
        v1: pavex::request::path::MatchedPathPattern,
        v2: &biscotti::Processor,
    ) -> pavex::response::Response {
        let v3 = crate::route_0::Next0 {
            s_0: v2,
            s_1: v1,
            s_2: v0,
            next: stage_1,
        };
        let v4 = pavex::middleware::Next::new(v3);
        let v5 = pavex::middleware::wrap_noop(v4).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v5)
    }
    async fn wrapping_1(
        v0: pavex::request::path::MatchedPathPattern,
        v1: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v2 = pavex::telemetry::ServerRequestId::generate();
        let v3 = app::telemetry::root_span(v1, v0, v2);
        let v4 = crate::route_0::Next1 {
            s_0: &v3,
            next: stage_2,
        };
        let v5 = pavex::middleware::Next::new(v4);
        let v6 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v3);
        let v7 = pavex_tracing::logger(v6, v5).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v7)
    }
    async fn handler() -> pavex::response::Response {
        let v0 = app::routes::ping::get();
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v0)
    }
    async fn post_processing_0(
        v0: pavex::response::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::response::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v2)
    }
    async fn post_processing_1(
        v0: pavex::response::Response,
        v1: &biscotti::Processor,
    ) -> pavex::response::Response {
        let v2 = pavex::cookie::ResponseCookies::new();
        let v3 = pavex::cookie::inject_response_cookies(v0, v2, v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::InjectResponseCookiesError::into_response(
                        &v4,
                    );
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v4)
    }
    struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a biscotti::Processor,
        s_1: pavex::request::path::MatchedPathPattern,
        s_2: &'b pavex::request::RequestHead,
        next: fn(
            &'a biscotti::Processor,
            pavex::request::path::MatchedPathPattern,
            &'b pavex::request::RequestHead,
        ) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2)
        }
    }
    struct Next1<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        next: fn(&'a pavex_tracing::RootSpan) -> T,
    }
    impl<'a, T> std::future::IntoFuture for Next1<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_1 {
    pub async fn entrypoint<'a, 'b, 'c, 'd>(
        s_0: pavex::request::path::RawPathParams<'a, 'b>,
        s_1: &'c biscotti::Processor,
        s_2: pavex::request::path::MatchedPathPattern,
        s_3: &'d pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3).await;
        response
    }
    async fn stage_1<'a, 'b, 'c, 'd>(
        s_0: pavex::request::path::RawPathParams<'a, 'b>,
        s_1: &'c pavex::request::RequestHead,
        s_2: &'d biscotti::Processor,
        s_3: pavex::request::path::MatchedPathPattern,
    ) -> pavex::response::Response {
        let response = wrapping_1(s_0, s_3, s_1).await;
        let response = post_processing_1(response, s_2).await;
        response
    }
    async fn stage_2<'a, 'b, 'c, 'd>(
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::path::RawPathParams<'b, 'c>,
        s_2: &'d pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let response = handler(s_0, s_1, s_2).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: pavex::request::path::RawPathParams<'_, '_>,
        v1: &biscotti::Processor,
        v2: pavex::request::path::MatchedPathPattern,
        v3: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v4 = crate::route_1::Next0 {
            s_0: v0,
            s_1: v3,
            s_2: v1,
            s_3: v2,
            next: stage_1,
        };
        let v5 = pavex::middleware::Next::new(v4);
        let v6 = pavex::middleware::wrap_noop(v5).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v6)
    }
    async fn wrapping_1(
        v0: pavex::request::path::RawPathParams<'_, '_>,
        v1: pavex::request::path::MatchedPathPattern,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = pavex::telemetry::ServerRequestId::generate();
        let v4 = app::telemetry::root_span(v2, v1, v3);
        let v5 = crate::route_1::Next1 {
            s_0: &v4,
            s_1: v0,
            s_2: v2,
            next: stage_2,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v4);
        let v8 = pavex_tracing::logger(v7, v6).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v8)
    }
    async fn handler(
        v0: &pavex_tracing::RootSpan,
        v1: pavex::request::path::RawPathParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = app::user_agent::UserAgent::extract(v2);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = app::user_agent::invalid_user_agent(&v4);
                    let v6 = pavex::Error::new(v4);
                    app::telemetry::error_logger(&v6, v0).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        let v5 = pavex::request::path::PathParams::extract(v1);
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = pavex::request::path::errors::ExtractPathParamsError::into_response(
                        &v6,
                    );
                    let v8 = pavex::Error::new(v6);
                    app::telemetry::error_logger(&v8, v0).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v7,
                    )
                };
            }
        };
        let v7 = app::routes::greet::get(v6, v4);
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v7)
    }
    async fn post_processing_0(
        v0: pavex::response::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::response::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v2)
    }
    async fn post_processing_1(
        v0: pavex::response::Response,
        v1: &biscotti::Processor,
    ) -> pavex::response::Response {
        let v2 = pavex::cookie::ResponseCookies::new();
        let v3 = pavex::cookie::inject_response_cookies(v0, v2, v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::InjectResponseCookiesError::into_response(
                        &v4,
                    );
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v4)
    }
    struct Next0<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::path::RawPathParams<'a, 'b>,
        s_1: &'c pavex::request::RequestHead,
        s_2: &'d biscotti::Processor,
        s_3: pavex::request::path::MatchedPathPattern,
        next: fn(
            pavex::request::path::RawPathParams<'a, 'b>,
            &'c pavex::request::RequestHead,
            &'d biscotti::Processor,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, T> std::future::IntoFuture for Next0<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3)
        }
    }
    struct Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::path::RawPathParams<'b, 'c>,
        s_2: &'d pavex::request::RequestHead,
        next: fn(
            &'a pavex_tracing::RootSpan,
            pavex::request::path::RawPathParams<'b, 'c>,
            &'d pavex::request::RequestHead,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, T> std::future::IntoFuture for Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2)
        }
    }
}
pub mod route_2 {
    pub async fn entrypoint<'a, 'b>(
        s_0: &'a biscotti::Processor,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: pavex::request::path::MatchedPathPattern,
        s_3: &'b pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3).await;
        response
    }
    async fn stage_1<'a, 'b>(
        s_0: &'a pavex::request::RequestHead,
        s_1: pavex::request::body::RawIncomingBody,
        mut s_2: pavex::cookie::ResponseCookies,
        s_3: &'b biscotti::Processor,
        s_4: pavex::request::path::MatchedPathPattern,
    ) -> pavex::response::Response {
        let response = wrapping_1(&mut s_2, s_1, s_4, s_0).await;
        let response = post_processing_1(response, s_2, s_3).await;
        response
    }
    async fn stage_2<'a, 'b, 'c>(
        s_0: &'a pavex_tracing::RootSpan,
        s_1: &'b pavex::request::RequestHead,
        s_2: pavex::request::body::RawIncomingBody,
        s_3: &'c mut pavex::cookie::ResponseCookies,
    ) -> pavex::response::Response {
        let response = handler(s_1, s_0, s_2, s_3).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: &biscotti::Processor,
        v1: pavex::request::body::RawIncomingBody,
        v2: pavex::request::path::MatchedPathPattern,
        v3: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v4 = pavex::cookie::ResponseCookies::new();
        let v5 = crate::route_2::Next0 {
            s_0: v3,
            s_1: v1,
            s_2: v4,
            s_3: v0,
            s_4: v2,
            next: stage_1,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = pavex::middleware::wrap_noop(v6).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v7)
    }
    async fn wrapping_1(
        v0: &mut pavex::cookie::ResponseCookies,
        v1: pavex::request::body::RawIncomingBody,
        v2: pavex::request::path::MatchedPathPattern,
        v3: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v4 = pavex::telemetry::ServerRequestId::generate();
        let v5 = app::telemetry::root_span(v3, v2, v4);
        let v6 = crate::route_2::Next1 {
            s_0: &v5,
            s_1: v3,
            s_2: v1,
            s_3: v0,
            next: stage_2,
        };
        let v7 = pavex::middleware::Next::new(v6);
        let v8 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v5);
        let v9 = pavex_tracing::logger(v8, v7).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v9)
    }
    async fn handler(
        v0: &pavex::request::RequestHead,
        v1: &pavex_tracing::RootSpan,
        v2: pavex::request::body::RawIncomingBody,
        v3: &mut pavex::cookie::ResponseCookies,
    ) -> pavex::response::Response {
        let v4 = <pavex::request::body::BodySizeLimit as std::default::Default>::default();
        let v5 = pavex::request::body::BufferedBody::extract(v0, v2, v4).await;
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v6,
                    );
                    let v8 = pavex::Error::new(v6);
                    app::telemetry::error_logger(&v8, v1).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v7,
                    )
                };
            }
        };
        let v7 = app::credentials::AuthStatus::extract(v0, &v6).await;
        let v8 = match v7 {
            Ok(ok) => ok,
            Err(v8) => {
                return {
                    let v9 = app::credentials::invalid_credentials(&v8);
                    let v10 = pavex::Error::new(v8);
                    app::telemetry::error_logger(&v10, v1).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v9,
                    )
                };
            }
        };
        let v9 = pavex::request::body::JsonBody::extract(v0, &v6);
        let v10 = match v9 {
            Ok(ok) => ok,
            Err(v10) => {
                return {
                    let v11 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v10,
                    );
                    let v12 = pavex::Error::new(v10);
                    app::telemetry::error_logger(&v12, v1).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v11,
                    )
                };
            }
        };
        let v11 = app::routes::login::post(&v10, v8, v3).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v11)
    }
    async fn post_processing_0(
        v0: pavex::response::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::response::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v2)
    }
    async fn post_processing_1(
        v0: pavex::response::Response,
        v1: pavex::cookie::ResponseCookies,
        v2: &biscotti::Processor,
    ) -> pavex::response::Response {
        let v3 = pavex::cookie::inject_response_cookies(v0, v1, v2);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::InjectResponseCookiesError::into_response(
                        &v4,
                    );
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v4)
    }
    struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex::request::RequestHead,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: pavex::cookie::ResponseCookies,
        s_3: &'b biscotti::Processor,
        s_4: pavex::request::path::MatchedPathPattern,
        next: fn(
            &'a pavex::request::RequestHead,
            pavex::request::body::RawIncomingBody,
            pavex::cookie::ResponseCookies,
            &'b biscotti::Processor,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
    struct Next1<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: &'b pavex::request::RequestHead,
        s_2: pavex::request::body::RawIncomingBody,
        s_3: &'c mut pavex::cookie::ResponseCookies,
        next: fn(
            &'a pavex_tracing::RootSpan,
            &'b pavex::request::RequestHead,
            pavex::request::body::RawIncomingBody,
            &'c mut pavex::cookie::ResponseCookies,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next1<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3)
        }
    }
}
pub mod route_3 {
    pub async fn entrypoint<'a, 'b, 'c>(
        s_0: &'a biscotti::Processor,
        s_1: &'b pavex::request::RequestHead,
        s_2: pavex::request::path::MatchedPathPattern,
        s_3: &'c pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3).await;
        response
    }
    async fn stage_1<'a, 'b, 'c>(
        s_0: &'a pavex::router::AllowedMethods,
        s_1: &'b biscotti::Processor,
        s_2: &'c pavex::request::RequestHead,
        s_3: pavex::request::path::MatchedPathPattern,
    ) -> pavex::response::Response {
        let response = wrapping_1(s_2, s_3, s_0).await;
        let response = post_processing_1(response, s_1).await;
        response
    }
    async fn stage_2<'a, 'b>(
        s_0: &'a pavex_tracing::RootSpan,
        s_1: &'b pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let response = handler(s_1).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: &biscotti::Processor,
        v1: &pavex::request::RequestHead,
        v2: pavex::request::path::MatchedPathPattern,
        v3: &pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let v4 = crate::route_3::Next0 {
            s_0: v3,
            s_1: v0,
            s_2: v1,
            s_3: v2,
            next: stage_1,
        };
        let v5 = pavex::middleware::Next::new(v4);
        let v6 = pavex::middleware::wrap_noop(v5).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v6)
    }
    async fn wrapping_1(
        v0: &pavex::request::RequestHead,
        v1: pavex::request::path::MatchedPathPattern,
        v2: &pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let v3 = pavex::telemetry::ServerRequestId::generate();
        let v4 = app::telemetry::root_span(v0, v1, v3);
        let v5 = crate::route_3::Next1 {
            s_0: &v4,
            s_1: v2,
            next: stage_2,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v4);
        let v8 = pavex_tracing::logger(v7, v6).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v8)
    }
    async fn handler(v0: &pavex::router::AllowedMethods) -> pavex::response::Response {
        let v1 = pavex::router::default_fallback(v0).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v1)
    }
    async fn post_processing_0(
        v0: pavex::response::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::response::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v2)
    }
    async fn post_processing_1(
        v0: pavex::response::Response,
        v1: &biscotti::Processor,
    ) -> pavex::response::Response {
        let v2 = pavex::cookie::ResponseCookies::new();
        let v3 = pavex::cookie::inject_response_cookies(v0, v2, v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::InjectResponseCookiesError::into_response(
                        &v4,
                    );
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v4)
    }
    struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex::router::AllowedMethods,
        s_1: &'b biscotti::Processor,
        s_2: &'c pavex::request::RequestHead,
        s_3: pavex::request::path::MatchedPathPattern,
        next: fn(
            &'a pavex::router::AllowedMethods,
            &'b biscotti::Processor,
            &'c pavex::request::RequestHead,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3)
        }
    }
    struct Next1<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: &'b pavex::router::AllowedMethods,
        next: fn(&'a pavex_tracing::RootSpan, &'b pavex::router::AllowedMethods) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next1<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1)
        }
    }
}
pub mod route_4 {
    pub async fn entrypoint<'a, 'b, 'c>(
        s_0: &'a app::configuration::ModelController,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b biscotti::Processor,
        s_3: pavex::request::path::MatchedPathPattern,
        s_4: &'c pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3, s_4).await;
        response
    }
    async fn stage_1<'a, 'b, 'c>(
        s_0: &'a pavex::request::RequestHead,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b app::configuration::ModelController,
        s_3: &'c biscotti::Processor,
        s_4: app::ctx::Ctx,
        s_5: pavex::request::path::MatchedPathPattern,
    ) -> pavex::response::Response {
        let response = wrapping_1(s_2, s_4, s_1, s_3, s_5, s_0).await;
        let response = post_processing_1(response, s_3).await;
        response
    }
    async fn stage_2<'a, 'b, 'c, 'd>(
        s_0: &'a pavex_tracing::RootSpan,
        s_1: &'b pavex::request::RequestHead,
        mut s_2: app::ctx::Ctx,
        s_3: pavex::request::body::RawIncomingBody,
        s_4: &'c app::configuration::ModelController,
        s_5: &'d biscotti::Processor,
    ) -> pavex::response::Response {
        if let Some(response) = pre_processing_0(s_1, s_5, &mut s_2)
            .await
            .into_response()
        {
            return response;
        }
        let response = handler(s_1, s_2, s_0, s_3, s_4).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: &app::configuration::ModelController,
        v1: pavex::request::body::RawIncomingBody,
        v2: &biscotti::Processor,
        v3: pavex::request::path::MatchedPathPattern,
        v4: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v5 = app::ctx::Ctx::new();
        let v6 = crate::route_4::Next0 {
            s_0: v4,
            s_1: v1,
            s_2: v0,
            s_3: v2,
            s_4: v5,
            s_5: v3,
            next: stage_1,
        };
        let v7 = pavex::middleware::Next::new(v6);
        let v8 = pavex::middleware::wrap_noop(v7).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v8)
    }
    async fn wrapping_1(
        v0: &app::configuration::ModelController,
        v1: app::ctx::Ctx,
        v2: pavex::request::body::RawIncomingBody,
        v3: &biscotti::Processor,
        v4: pavex::request::path::MatchedPathPattern,
        v5: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v6 = pavex::telemetry::ServerRequestId::generate();
        let v7 = app::telemetry::root_span(v5, v4, v6);
        let v8 = crate::route_4::Next1 {
            s_0: &v7,
            s_1: v5,
            s_2: v1,
            s_3: v2,
            s_4: v0,
            s_5: v3,
            next: stage_2,
        };
        let v9 = pavex::middleware::Next::new(v8);
        let v10 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v7);
        let v11 = pavex_tracing::logger(v10, v9).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v11)
    }
    async fn pre_processing_0(
        v0: &pavex::request::RequestHead,
        v1: &biscotti::Processor,
        v2: &mut app::ctx::Ctx,
    ) -> pavex::middleware::Processing<pavex::response::Response> {
        let v3 = pavex::cookie::extract_request_cookies(v0, v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::ExtractRequestCookiesError::into_response(
                        &v4,
                    );
                    let v6 = <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    );
                    pavex::middleware::Processing::EarlyReturn(v6)
                };
            }
        };
        let v5 = app::routes::web::mw_auth::mw_require_auth(v4, v2).await;
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = app::routes::web::mw_auth::mw_auth_error(&v6).await;
                    let v8 = <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v7,
                    );
                    pavex::middleware::Processing::EarlyReturn(v8)
                };
            }
        };
        v6
    }
    async fn handler(
        v0: &pavex::request::RequestHead,
        v1: app::ctx::Ctx,
        v2: &pavex_tracing::RootSpan,
        v3: pavex::request::body::RawIncomingBody,
        v4: &app::configuration::ModelController,
    ) -> pavex::response::Response {
        let v5 = <pavex::request::body::BodySizeLimit as std::default::Default>::default();
        let v6 = pavex::request::body::BufferedBody::extract(v0, v3, v5).await;
        let v7 = match v6 {
            Ok(ok) => ok,
            Err(v7) => {
                return {
                    let v8 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v7,
                    );
                    let v9 = pavex::Error::new(v7);
                    app::telemetry::error_logger(&v9, v2).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v8,
                    )
                };
            }
        };
        let v8 = app::tickets::TicketForCreate::extract(v0, &v7);
        let v9 = match v8 {
            Ok(ok) => ok,
            Err(v9) => {
                return {
                    let v10 = app::tickets::invalid_ticket(&v9);
                    let v11 = pavex::Error::new(v9);
                    app::telemetry::error_logger(&v11, v2).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v10,
                    )
                };
            }
        };
        let v10 = app::routes::web::tickets::post(v4, v1, v9).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v10)
    }
    async fn post_processing_0(
        v0: pavex::response::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::response::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v2)
    }
    async fn post_processing_1(
        v0: pavex::response::Response,
        v1: &biscotti::Processor,
    ) -> pavex::response::Response {
        let v2 = pavex::cookie::ResponseCookies::new();
        let v3 = pavex::cookie::inject_response_cookies(v0, v2, v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::InjectResponseCookiesError::into_response(
                        &v4,
                    );
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v4)
    }
    struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex::request::RequestHead,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b app::configuration::ModelController,
        s_3: &'c biscotti::Processor,
        s_4: app::ctx::Ctx,
        s_5: pavex::request::path::MatchedPathPattern,
        next: fn(
            &'a pavex::request::RequestHead,
            pavex::request::body::RawIncomingBody,
            &'b app::configuration::ModelController,
            &'c biscotti::Processor,
            app::ctx::Ctx,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4, self.s_5)
        }
    }
    struct Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: &'b pavex::request::RequestHead,
        s_2: app::ctx::Ctx,
        s_3: pavex::request::body::RawIncomingBody,
        s_4: &'c app::configuration::ModelController,
        s_5: &'d biscotti::Processor,
        next: fn(
            &'a pavex_tracing::RootSpan,
            &'b pavex::request::RequestHead,
            app::ctx::Ctx,
            pavex::request::body::RawIncomingBody,
            &'c app::configuration::ModelController,
            &'d biscotti::Processor,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, T> std::future::IntoFuture for Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4, self.s_5)
        }
    }
}
pub mod route_5 {
    pub async fn entrypoint<'a, 'b, 'c>(
        s_0: &'a pavex::request::RequestHead,
        s_1: &'b biscotti::Processor,
        s_2: pavex::request::path::MatchedPathPattern,
        s_3: &'c app::configuration::ModelController,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3).await;
        response
    }
    async fn stage_1<'a, 'b, 'c>(
        s_0: &'a app::configuration::ModelController,
        s_1: &'b pavex::request::RequestHead,
        s_2: &'c biscotti::Processor,
        s_3: app::ctx::Ctx,
        s_4: pavex::request::path::MatchedPathPattern,
    ) -> pavex::response::Response {
        let response = wrapping_1(s_3, s_1, s_2, s_4, s_0).await;
        let response = post_processing_1(response, s_2).await;
        response
    }
    async fn stage_2<'a, 'b, 'c, 'd>(
        s_0: &'a pavex_tracing::RootSpan,
        mut s_1: app::ctx::Ctx,
        s_2: &'b app::configuration::ModelController,
        s_3: &'c pavex::request::RequestHead,
        s_4: &'d biscotti::Processor,
    ) -> pavex::response::Response {
        if let Some(response) = pre_processing_0(s_3, s_4, &mut s_1)
            .await
            .into_response()
        {
            return response;
        }
        let response = handler(s_1, s_2).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: &pavex::request::RequestHead,
        v1: &biscotti::Processor,
        v2: pavex::request::path::MatchedPathPattern,
        v3: &app::configuration::ModelController,
    ) -> pavex::response::Response {
        let v4 = app::ctx::Ctx::new();
        let v5 = crate::route_5::Next0 {
            s_0: v3,
            s_1: v0,
            s_2: v1,
            s_3: v4,
            s_4: v2,
            next: stage_1,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = pavex::middleware::wrap_noop(v6).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v7)
    }
    async fn wrapping_1(
        v0: app::ctx::Ctx,
        v1: &pavex::request::RequestHead,
        v2: &biscotti::Processor,
        v3: pavex::request::path::MatchedPathPattern,
        v4: &app::configuration::ModelController,
    ) -> pavex::response::Response {
        let v5 = pavex::telemetry::ServerRequestId::generate();
        let v6 = app::telemetry::root_span(v1, v3, v5);
        let v7 = crate::route_5::Next1 {
            s_0: &v6,
            s_1: v0,
            s_2: v4,
            s_3: v1,
            s_4: v2,
            next: stage_2,
        };
        let v8 = pavex::middleware::Next::new(v7);
        let v9 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v6);
        let v10 = pavex_tracing::logger(v9, v8).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v10)
    }
    async fn pre_processing_0(
        v0: &pavex::request::RequestHead,
        v1: &biscotti::Processor,
        v2: &mut app::ctx::Ctx,
    ) -> pavex::middleware::Processing<pavex::response::Response> {
        let v3 = pavex::cookie::extract_request_cookies(v0, v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::ExtractRequestCookiesError::into_response(
                        &v4,
                    );
                    let v6 = <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    );
                    pavex::middleware::Processing::EarlyReturn(v6)
                };
            }
        };
        let v5 = app::routes::web::mw_auth::mw_require_auth(v4, v2).await;
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = app::routes::web::mw_auth::mw_auth_error(&v6).await;
                    let v8 = <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v7,
                    );
                    pavex::middleware::Processing::EarlyReturn(v8)
                };
            }
        };
        v6
    }
    async fn handler(
        v0: app::ctx::Ctx,
        v1: &app::configuration::ModelController,
    ) -> pavex::response::Response {
        let v2 = app::routes::web::tickets::get(v1, v0).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v2)
    }
    async fn post_processing_0(
        v0: pavex::response::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::response::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v2)
    }
    async fn post_processing_1(
        v0: pavex::response::Response,
        v1: &biscotti::Processor,
    ) -> pavex::response::Response {
        let v2 = pavex::cookie::ResponseCookies::new();
        let v3 = pavex::cookie::inject_response_cookies(v0, v2, v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::InjectResponseCookiesError::into_response(
                        &v4,
                    );
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v4)
    }
    struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a app::configuration::ModelController,
        s_1: &'b pavex::request::RequestHead,
        s_2: &'c biscotti::Processor,
        s_3: app::ctx::Ctx,
        s_4: pavex::request::path::MatchedPathPattern,
        next: fn(
            &'a app::configuration::ModelController,
            &'b pavex::request::RequestHead,
            &'c biscotti::Processor,
            app::ctx::Ctx,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
    struct Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: app::ctx::Ctx,
        s_2: &'b app::configuration::ModelController,
        s_3: &'c pavex::request::RequestHead,
        s_4: &'d biscotti::Processor,
        next: fn(
            &'a pavex_tracing::RootSpan,
            app::ctx::Ctx,
            &'b app::configuration::ModelController,
            &'c pavex::request::RequestHead,
            &'d biscotti::Processor,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, T> std::future::IntoFuture for Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
}
pub mod route_6 {
    pub async fn entrypoint<'a, 'b, 'c, 'd, 'e>(
        s_0: pavex::request::path::RawPathParams<'a, 'b>,
        s_1: &'c pavex::request::RequestHead,
        s_2: &'d biscotti::Processor,
        s_3: pavex::request::path::MatchedPathPattern,
        s_4: &'e app::configuration::ModelController,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3, s_4).await;
        response
    }
    async fn stage_1<'a, 'b, 'c, 'd, 'e>(
        s_0: pavex::request::path::RawPathParams<'a, 'b>,
        s_1: &'c app::configuration::ModelController,
        s_2: &'d pavex::request::RequestHead,
        s_3: &'e biscotti::Processor,
        s_4: app::ctx::Ctx,
        s_5: pavex::request::path::MatchedPathPattern,
    ) -> pavex::response::Response {
        let response = wrapping_1(s_4, s_0, s_2, s_3, s_5, s_1).await;
        let response = post_processing_1(response, s_3).await;
        response
    }
    async fn stage_2<'a, 'b, 'c, 'd, 'e, 'f>(
        s_0: &'a pavex_tracing::RootSpan,
        mut s_1: app::ctx::Ctx,
        s_2: pavex::request::path::RawPathParams<'b, 'c>,
        s_3: &'d app::configuration::ModelController,
        s_4: &'e pavex::request::RequestHead,
        s_5: &'f biscotti::Processor,
    ) -> pavex::response::Response {
        if let Some(response) = pre_processing_0(s_4, s_5, &mut s_1)
            .await
            .into_response()
        {
            return response;
        }
        let response = handler(s_0, s_1, s_2, s_3).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: pavex::request::path::RawPathParams<'_, '_>,
        v1: &pavex::request::RequestHead,
        v2: &biscotti::Processor,
        v3: pavex::request::path::MatchedPathPattern,
        v4: &app::configuration::ModelController,
    ) -> pavex::response::Response {
        let v5 = app::ctx::Ctx::new();
        let v6 = crate::route_6::Next0 {
            s_0: v0,
            s_1: v4,
            s_2: v1,
            s_3: v2,
            s_4: v5,
            s_5: v3,
            next: stage_1,
        };
        let v7 = pavex::middleware::Next::new(v6);
        let v8 = pavex::middleware::wrap_noop(v7).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v8)
    }
    async fn wrapping_1(
        v0: app::ctx::Ctx,
        v1: pavex::request::path::RawPathParams<'_, '_>,
        v2: &pavex::request::RequestHead,
        v3: &biscotti::Processor,
        v4: pavex::request::path::MatchedPathPattern,
        v5: &app::configuration::ModelController,
    ) -> pavex::response::Response {
        let v6 = pavex::telemetry::ServerRequestId::generate();
        let v7 = app::telemetry::root_span(v2, v4, v6);
        let v8 = crate::route_6::Next1 {
            s_0: &v7,
            s_1: v0,
            s_2: v1,
            s_3: v5,
            s_4: v2,
            s_5: v3,
            next: stage_2,
        };
        let v9 = pavex::middleware::Next::new(v8);
        let v10 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v7);
        let v11 = pavex_tracing::logger(v10, v9).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v11)
    }
    async fn pre_processing_0(
        v0: &pavex::request::RequestHead,
        v1: &biscotti::Processor,
        v2: &mut app::ctx::Ctx,
    ) -> pavex::middleware::Processing<pavex::response::Response> {
        let v3 = pavex::cookie::extract_request_cookies(v0, v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::ExtractRequestCookiesError::into_response(
                        &v4,
                    );
                    let v6 = <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    );
                    pavex::middleware::Processing::EarlyReturn(v6)
                };
            }
        };
        let v5 = app::routes::web::mw_auth::mw_require_auth(v4, v2).await;
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = app::routes::web::mw_auth::mw_auth_error(&v6).await;
                    let v8 = <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v7,
                    );
                    pavex::middleware::Processing::EarlyReturn(v8)
                };
            }
        };
        v6
    }
    async fn handler(
        v0: &pavex_tracing::RootSpan,
        v1: app::ctx::Ctx,
        v2: pavex::request::path::RawPathParams<'_, '_>,
        v3: &app::configuration::ModelController,
    ) -> pavex::response::Response {
        let v4 = pavex::request::path::PathParams::extract(v2);
        let v5 = match v4 {
            Ok(ok) => ok,
            Err(v5) => {
                return {
                    let v6 = pavex::request::path::errors::ExtractPathParamsError::into_response(
                        &v5,
                    );
                    let v7 = pavex::Error::new(v5);
                    app::telemetry::error_logger(&v7, v0).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v6,
                    )
                };
            }
        };
        let v6 = app::routes::web::tickets::delete(v3, v1, v5).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v6)
    }
    async fn post_processing_0(
        v0: pavex::response::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::response::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v2)
    }
    async fn post_processing_1(
        v0: pavex::response::Response,
        v1: &biscotti::Processor,
    ) -> pavex::response::Response {
        let v2 = pavex::cookie::ResponseCookies::new();
        let v3 = pavex::cookie::inject_response_cookies(v0, v2, v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::InjectResponseCookiesError::into_response(
                        &v4,
                    );
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v4)
    }
    struct Next0<'a, 'b, 'c, 'd, 'e, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::path::RawPathParams<'a, 'b>,
        s_1: &'c app::configuration::ModelController,
        s_2: &'d pavex::request::RequestHead,
        s_3: &'e biscotti::Processor,
        s_4: app::ctx::Ctx,
        s_5: pavex::request::path::MatchedPathPattern,
        next: fn(
            pavex::request::path::RawPathParams<'a, 'b>,
            &'c app::configuration::ModelController,
            &'d pavex::request::RequestHead,
            &'e biscotti::Processor,
            app::ctx::Ctx,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, 'e, T> std::future::IntoFuture for Next0<'a, 'b, 'c, 'd, 'e, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4, self.s_5)
        }
    }
    struct Next1<'a, 'b, 'c, 'd, 'e, 'f, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: app::ctx::Ctx,
        s_2: pavex::request::path::RawPathParams<'b, 'c>,
        s_3: &'d app::configuration::ModelController,
        s_4: &'e pavex::request::RequestHead,
        s_5: &'f biscotti::Processor,
        next: fn(
            &'a pavex_tracing::RootSpan,
            app::ctx::Ctx,
            pavex::request::path::RawPathParams<'b, 'c>,
            &'d app::configuration::ModelController,
            &'e pavex::request::RequestHead,
            &'f biscotti::Processor,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, 'e, 'f, T> std::future::IntoFuture
    for Next1<'a, 'b, 'c, 'd, 'e, 'f, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4, self.s_5)
        }
    }
}
